### ISSUE TITLE
Support tslint-config-prettier

### ISSUE THREAD

**Issue by WillSquire** [nestjs/typescript-starter#141]
Just started using the framework and noticed that both tslint and prettier are setup, but aren't working with each other. By default they play nice, however if the tslint or prettier settings are changed they can conflict with one another. There's a module called `tslint-config-prettier` that integrates both settings together so these always play nice. This means the settings can be updated without issue :)

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue :)?

**Comment by kamilmysliwiec** [comment]
We're going to move to eslint shortly anyway. Let's close this issue then
