### ISSUE TITLE
FAIL test/app.e2e-spec.ts

### ISSUE THREAD

**Issue by Domiserver** [nestjs/typescript-starter#145]
Hi Kamil,

I hope this can helpful to others using NestJS.  An hour ago I installed NestJs in a new project.  When I ran $npm run test:e2e the "Test suite failed to run. error TS2349".

This is what I did to solve this issue:
a) Updated "jest" from v23.6.0 to v24.8.0
b) Edited line from "import * as request from 'supertest'; " to "import request from 'supertest'; "

Then the test:e2e: "PASS => Ran all test suites"
Regards and thanks for the NestJs platform.
Ronald

**Comment by kamilmysliwiec** [comment]
What's your TypeScript version?

**Comment by Domiserver** [comment]
typescript 3.4.3
Everything is now running smoothly with $npm run test: e2e. Thanks so much.
====================

Dear Kamil excuse me for going off on a tangent:  I am working on Nestjs Authentication.    

The line after @Injectable "export class JwtStrategy extends PassportStrategy(Strategy)"   is telling me "Expected 2 arguments, but got 1 => An argument for 'name' was not provided"

You can get this error, even if you copy and paste directly from the Documentation at: 
https://docs.nestjs.com/techniques/authentication

For the last couple of hours, I google but I have not had any success in fixing this error ts2554.
Have you seen this issue before with Nestjs?
