### ISSUE TITLE
Vulnerabilty in jest package and outdated packages

### ISSUE THREAD

**Issue by rubiin** [nestjs/typescript-starter#152]
While running npm install, jest package seems to be having a vulnerable handlebar dependency. The fix is availabe , I can do pr if you like

**Comment by rubiin** [comment]
![Screenshot from 2019-09-30 22-37-58](https://user-images.githubusercontent.com/8222059/65899287-23d0c580-e3d3-11e9-91ee-8a1caeb585c6.png)

**Comment by rubiin** [comment]
@kamilmysliwiec

**Comment by kamilmysliwiec** [comment]
PRs are welcome

**Comment by rubiin** [comment]
Here is the PR with the fix https://github.com/nestjs/typescript-starter/pull/153

**Comment by kamilmysliwiec** [comment]
Thank you!!
