### ISSUE TITLE
npm run start not working

### ISSUE THREAD

**Issue by BrucePauker** [nestjs/typescript-starter#154]
Hello,

I have some issues running this script. I just cloned it on my local machine, i run:
`npm install`

and then i run :
`npm run start`

And I have this error : 

> internal/modules/cjs/loader.js:584
    throw err;
    ^
Error: Cannot find module 'C:\Users\Bruce'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

I did nothing else, and I really don't understand why... Moreover this error only appears on windows. Could you help me ?

Thanks !

**Comment by Omnyx** [comment]
Same here. Tried doing nest new project and also cloning this repo but I am having the same errors without adding anything to the code.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by BrucePauker** [comment]
The minimal repository is this repository. I just cloned it, ran `npm i` and `npm run start` and it failed. with the error above.

**Comment by kamilmysliwiec** [comment]
What is your full path to the dist folder?

**Comment by BrucePauker** [comment]
C:\Users\Bruce Pauker\Aphilia\development\test\app\dist

**Comment by kamilmysliwiec** [comment]
Please, update your `@nestjs/cli` package into 6.11.2 version and let me know if you face any issue.
