### ISSUE TITLE
Sourcemaps detection when start from docker is not working.

### ISSUE THREAD

**Issue by Bilchuck** [nestjs/typescript-starter#157]
When I try to start application on debug mode `nest start --debug 0.0.0.0` from docker and connect to debugger via chrome-inspector I can only see `.js` files there but no `.ts` files.

Branch to reproduce: https://github.com/Bilchuck/typescript-starter

Run `docker-compose up`

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
