### ISSUE TITLE
Rimraf in dependencies

### ISSUE THREAD

**Issue by maca134** [nestjs/typescript-starter#158]
Doesnt rimraf belong in devDependencies

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/typescript-starter/issues/135#issuecomment-494731806

**Comment by imgx64** [comment]
@kamilmysliwiec Sorry for replying to an old issue, but isn't that comment invalid since d54bf6f? I don't see any reason not to move rimraf to devDependencies.

**Comment by cpmachado** [comment]
@imgx64 I have the same question.
