### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by xavi-dev** [nestjs/typescript-starter#159]
The very first time after clonning this repo, you won't be able to run `npm run start:prod` due to the changes done in [this commit](https://github.com/nestjs/typescript-starter/commit/d54bf6f8c23ff2f3d594ef04b1829287aa8d73f6#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

Do I have to run `npm run build` before? or there is some missing 'prestart:prod' script?

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/typescript-starter/issues/135
