### ISSUE TITLE
How to Debug NestJs in WebStorm

### ISSUE THREAD

**Issue by ankurpathak** [nestjs/typescript-starter#165]
Please don't close this issue like earlier once.
Please provide detailed explanation to debug nestjs in all major ide used.

**Comment by jmcdo29** [comment]
Nest provides a `start:debug` command that adds an `--insert-brk` to the main `node` command, which means that you can attach a debugger to port `9229` (the default debug port) and have a debugger listening for any breakpoints and/or exceptions. You can change this port with the `--debug` flag and passing the port right after it. From there, [Webstorm's Documentation](https://www.jetbrains.com/help/webstorm/running-and-debugging-node-js.html#257268d5) should be enough to get things going.
