### ISSUE TITLE
Compiling Error: Import does not exist on @Module

### ISSUE THREAD

**Issue by williamchristophercooley** [nestjs/typescript-starter#17]
When builds try to compiler the Typescript Im getting that looks like the Module definition.

**Impacted File**: app.module.ts (the main core module)

**Terminal Error:**
`17:20:50   Object literal may only specify known properties, and 'imports' does not exist in type '{ modules?: any[]; controllers?: any[]; components?: any[]; exports?: any[]; }'.`

**Node Version:** 9.0.0

**Package.json**
```
  "dependencies": {
    "@nestjs/common": "^4.0.2",
    "@nestjs/core": "^4.0.2",
    "@nestjs/microservices": "^4.0.2",
    "@nestjs/swagger": "^1.1.3",
    "@nestjs/testing": "^4.0.2",
    "@nestjs/websockets": "^4.0.2",
    "@types/morgan": "^1.7.35",
    "aws-sdk": "^2.180.0",
    "cookie-parser": "^1.4.3",
    "jsrsasign": "^8.0.4",
    "lodash.defaultsdeep": "~4.6.0",
    "morgan": "^1.9.0",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.4.3"
  },
  "devDependencies": {
    "@types/chai": "^4.0.2",
    "@types/express": "^4.0.36",
    "@types/mocha": "^2.2.41",
    "@types/node": "^9.3.0",
    "@types/sinon": "^2.3.3",
    "chai": "^4.1.1",
    "mocha": "^3.5.0",
    "nodemon": "^1.11.0",
    "sinon": "^2.4.1",
    "ts-node": "^4.1.0",
    "tsconfig-paths": "^3.1.1",
    "typescript": "^2.4.2"
  }
```

**Comment by stormpat** [comment]
Same issue

**Comment by kamilmysliwiec** [comment]
Hi @stormpat @williamchristophercooley,
You need to update your Nest version (the latest one is `v4.5.10`). I have pushed `package.json` update into this repo so you can pull changes easily. 🙂

**Comment by williamchristophercooley** [comment]
@kamilmysliwiec what about swagger?
