### ISSUE TITLE
tsconfig.json exclude setting is not necessary because it is already handled by defaults

### ISSUE THREAD

**Issue by msheakoski** [nestjs/typescript-starter#170]
The `exclude` setting in tsconfig.json is not necessary because the TypeScript default value already covers the same directories.

https://github.com/nestjs/typescript-starter/blob/08b0150cb67d66a3b5654059ac2c15423ec77764/tsconfig.json#L14

From the [TypeScript docs for the exclude setting](https://www.staging-typescript.org/tsconfig#exclude):

> `["node_modules", "bower_components", "jspm_packages"]`, plus the value of `outDir` if one is specified.

**Comment by kamilmysliwiec** [comment]
Fixed
