### ISSUE TITLE
TypeORM - Entity not loaded if specified in the ormconfig.json

### ISSUE THREAD

**Issue by baskaranfqa** [nestjs/typescript-starter#173]
TypeORM - Entity not loaded if specified in the ormconfig.json

````
{
    "type": "mysql",
    "host": "localhost",
    "port": 3306,
    "username": "db_user",
    "password": "db_user_29292",
    "database": "xyzdb",
    "entities": ["dist/**/*.entity{.ts,.js}"],
    "synchronize": true
  }
````
as dist/main.js created on the build, so the entities not loaded

**`"entities": ["dist/**/*.entity{.ts,.js}"],`**

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
