### ISSUE TITLE
Docker files are being ignored in .gitignore

### ISSUE THREAD

**Issue by hiagodotme** [nestjs/typescript-starter#181]
Hello guys, I'm starting the development of a new project. I chose nestjs because honestly it is the most complete framework I have ever seen, I really liked the documentation and the ecosystem.

I noticed something strange, I created a `docker-compose.yml` file and it is being ignored in the `.gitignore` file.

Are there any specific reasons for this? In our environment the node runs inside containers so that you don't have to install dependencies on the machines. In addition to the fact that continuous integration is part of the project, I believe that ignoring this file is not correct.

Thanks to personal attention!

**Comment by kamilmysliwiec** [comment]
Fixed https://github.com/nestjs/typescript-starter/pull/182
