### ISSUE TITLE
Add "skipLibCheck": true, to tsconfig.json

### ISSUE THREAD

**Issue by mateushnsoares** [nestjs/typescript-starter#183]
I prefer to have this option because not always all libraries are with all code correct I think that you need to check only your application.

Come on to discuss if it makes sense to the boilerplate or no.

**Comment by kamilmysliwiec** [comment]
Feel free to change `skipLibCheck` to `true` if you want. It's up to developers to adjust their configuration to the team's needs. We suggest using `false` though and we don't plan to change it in the near future.
