### ISSUE TITLE
Reflector not injected.

### ISSUE THREAD

**Issue by ramachandrann** [nestjs/typescript-starter#19]
Hello there, 
I followed the tutorial to create a role guard with reflector injected https://docs.nestjs.com/guards
At runtime, nest throws an exception where we call .get() like so. 
const roles = this.reflector.get<string[]>('roles', handler);
Looks like injector was not made available.

[Nest] 5448   - 2018-2-2 13:23:52   [ExceptionsHandler] Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined at RoleGuard.canActivate (C:\Users\nest\project\src\core\role.guard.ts:11:34) https://docs.nestjs.com/guards

Can you pls check it out?

Dependencies/versions in package.json
"dependencies": {
    "@nestjs/common": "^4.5.9",
    "@nestjs/core": "^4.5.10",
    "@nestjs/microservices": "^4.5.8",
    "@nestjs/testing": "^4.5.5",
    "@nestjs/websockets": "^4.5.8",
    "@types/express-jwt": "0.0.38",
    "body-parser": "^1.18.2",
    "express-jwt": "^5.3.0",
    "jwks-rsa": "^1.2.1",
    "redis": "^2.7.1",
    "reflect-metadata": "^0.1.12",
    "rxjs": "^5.5.6",
    "typescript": "^2.6.2"
  }

**Comment by kamilmysliwiec** [comment]
Hi @ramachandrann,
Please, report an issue in the main repo https://github.com/nestjs/nest
