### ISSUE TITLE
tslint is missing in dev dependencies

### ISSUE THREAD

**Issue by icepeng** [nestjs/typescript-starter#20]
`tsconfig.json` is existing in this repo, but tslint would not work before installing manually.

Is this behavior intended?

**Comment by alsoicode** [comment]
@icepeng I typically install tslint as a global dependency and don't include it in package.json.

**Comment by e-watson** [comment]
As for me, better to add tslint into dev dependencies... and maybe remove redis? ;-)

**Comment by kamilmysliwiec** [comment]
Done. Thanks!
