### ISSUE TITLE
Is tsconfig.build.json still needed ?

### ISSUE THREAD

**Issue by DevDengChao** [nestjs/typescript-starter#213]
`tsconfig.build.json` is introduced in commit 1b81bde89e4ff318c6b66accf899097ae960944b , and it seems like the author is testing something with it and forget to remove it later.

Dose it still needed in new project by default ? 

I created a new project by `nest new my-project`, and I found this file is not referenced anywhere, so I came here and created this issue.

**Comment by jmcdo29** [comment]
`tsconfig.build.json` is actually the config file used by the `nest build` command and passed on to `tsc` for compilation options. If you remove it, you'll notice the command doesn't work anymore

**Comment by DevDengChao** [comment]
Thanks for your explaination.

**Comment by micalevisk** [comment]
you can merge it with `tsconfig.json` (and change the `build` npm-script to `nest build -p tsconfig.json`) but then you will need to write another tsconfig to deal with `.spec.ts` files (for development purposes).
