### ISSUE TITLE
Add tsconfig-paths to project

### ISSUE THREAD

**Issue by xipheCom** [nestjs/typescript-starter#22]
## I'm submitting a...
[ ] Regression 
[ ] Bug report
[ X ] Feature request

## Current behavior
`paths` section in tsconfig.json is ignored by ts-node, you will need tsconfig-paths for it.  
## Expected behavior
'paths' section will be recognized

## Minimal reproduction of the problem with instructions
```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@shared/*": [
        "../shared/*"
      ],
      "@libs/*": [
        "../libs/*"
      ]
    }
  },
 ...
```

```typescript
import { Foo } from '@shared/foo'
```
--> Module not found

**Comment by kamilmysliwiec** [comment]
PR merged
