### ISSUE TITLE
Makes sense have an example of Clean Architecture on this (or on other) repo implemented?

### ISSUE THREAD

**Issue by ologbonowiwi** [nestjs/typescript-starter#226]
I've implemented 4 different projects with nest using clean architecture and want to know if makes sense have this on nestjs project.
What u say about that guys? 🤔

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
