### ISSUE TITLE
How to remove the Label "Nest framework TypeScript starter repository" in Swagger Doc?

### ISSUE THREAD

**Issue by honigkuchenbaer** [nestjs/typescript-starter#232]
The Swagger Doc renders automatically the following sentence:

"[Nest](https://github.com/nestjs/nest) framework TypeScript starter repository"

Can we change this somehow with our own introduction?

<img width="466" alt="Screenshot 2022-04-09 at 13 23 28" src="https://user-images.githubusercontent.com/50707097/162569731-fa8f7849-2f50-47ee-890e-a7a75169db52.png">

**Comment by itinance** [comment]
In `main.ts` you should have code like the following:

```
  const swaggerConfig = new DocumentBuilder()
    .setTitle(title)
    .setDescription(process.env.npm_package_description)
    .setVersion(version)
    .build();
```

`setDescription` is the method of your choice to change this text in question.
