### ISSUE TITLE
Consider additional maintainers?

### ISSUE THREAD

**Issue by alsoicode** [nestjs/typescript-starter#27]
As the maintainer of several open source projects myself in addition to having a full-time job and family, time is sometimes in short supply. Fortunately, my wife is a very understanding, kind soul who gives me plenty of time to code :)

I, and I'm sure other, would like to be able to contribute to Nest and keep it moving forward. Would you be interested in bringing on some additional maintainers?

**Comment by kamilmysliwiec** [comment]
Hi @alsoicode,
Sure! Since the v5 development is almost entirely done, I'll look for help then. Please, give me a little bit more time to bring remaining stuff asap 🙂
