### ISSUE TITLE
Imports order as a part of eslint and prettier

### ISSUE THREAD

**Issue by vahidvdn** [nestjs/typescript-starter#286]
I believe the order of imports in typescript is a big step toward clean code and it can be a part of eslint and prettier in nestjs starter by default. More info can be found here:

https://medium.com/weekly-webtips/how-to-sort-imports-like-a-pro-in-typescript-4ee8afd7258a

**Comment by Neosoulink** [comment]
@vahidvdn. Yeah, It looks cool and easy to implement... But I don't know if it's necessary to add one or maybe 2 more dependencies just to sort the order of imports...

It may break the code style of some devs who like to order the imports by blocks

**Comment by vahidvdn** [comment]
@Neosoulink That makes sense to me. Thanks for sharing your idea.
Therefore, closing this issue
