### ISSUE TITLE
Add `lib` field in `tsconfig.json` to exclude dom related apis explicitly.

### ISSUE THREAD

**Issue by rick-ast** [nestjs/typescript-starter#288]
Since nestjs should not use dom related apis, maybe it would be better to explicitly eliminate it?
```jsonc
{
  ...,
  "lib": ["ESNext"]
}
```
Add this config to tsconfig.json file, when you use window it would display error message.
<img width="386" alt="截屏2023-11-01 22 47 09" src="https://github.com/nestjs/typescript-starter/assets/130942798/8288e39e-07c1-4aea-96db-4d90ae7de18f">

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by rick-ast** [comment]
Hi @kamilmysliwiec , I ceated a PR https://github.com/nestjs/typescript-starter/pull/289, please help to review.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/typescript-starter/pull/289
