### ISSUE TITLE
References to incorrect peer dependency reflect-metadata@0.1.10

### ISSUE THREAD

**Issue by e-watson** [nestjs/typescript-starter#29]
Current package.json dev packages has strict references to reflect-metadata@0.1.10 e.g.

warning " > @nestjs/common@4.6.5" has incorrect peer dependency "reflect-metadata@0.1.10".
warning " > @nestjs/core@4.6.5" has incorrect peer dependency "reflect-metadata@0.1.10".
warning " > @nestjs/microservices@4.6.5" has incorrect peer dependency "reflect-metadata@0.1.10".
warning " > @nestjs/websockets@4.6.5" has incorrect peer dependency "reflect-metadata@0.1.10".

Let's change reference in package.json to "reflect-metadata": "0.1.10" or remove this strict reference inside packages
@nestjs/common@4.6.5
@nestjs/core@4.6.5
@nestjs/microservices@4.6.5
@nestjs/websockets@4.6.5

**Comment by kamilmysliwiec** [comment]
This issue is solved within an incoming release. Thanks for reporting.
