### ISSUE TITLE
npm run start:prod thrown error.

### ISSUE THREAD

**Issue by miladhashemi** [nestjs/typescript-starter#293]
### Issue:
Running `npm run start:prod` causes throw following error: 

```
Error: Cannot find module '/home/hesaba/Milad/Workspace/chehreh2-normal-control-consumer/dist/main'
```

### Solution:
`start:prod` script value must be updated from `dist/main` to `dist/src/main`

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
