### ISSUE TITLE
How i can debug in Webstorm with nodemon ?

### ISSUE THREAD

**Issue by alikdelrisco92** [nestjs/typescript-starter#30]
How i can debug in Webstorm with nodemon ?

**Comment by kamilmysliwiec** [comment]
Hi,
In the nearest future, I'll publish a set of articles how to work with nest easily.

**Comment by ShinDarth** [comment]
any news about this? I'm looking for instructions to run & debug with IntelliJ/Webstorm

**Comment by kwtsangaf** [comment]
how can I debug in the newest version, 5.0.0? Is there any way to debug ts-node in windows environment? thank you.

**Comment by alikdelrisco92** [comment]
add `--inspect=5858` in nodemon.json 
this is my nodemon.json:
 `{
  "watch": [
    "src"
  ],
  "ext": "ts",
  "ignore": [
    "src/**/*.spec.ts"
  ],
  "exec": "ts-node --inspect=5858 -r tsconfig-paths/register src/main.hmr.ts"
}`
 and then in webstorm add configuration like this 
![screenshot from 2018-05-16 13-17-02](https://user-images.githubusercontent.com/28146758/40132758-a9c63764-590b-11e8-8c62-ea085b5994f7.png)

**Comment by kwtsangaf** [comment]
It works! Thank you!

**Comment by ShinDarth** [comment]
ideally this kind of stuff should be documented elsewhere (either the official doc or stackoverflow), I don't think github issues are a good place for it

**Comment by kherel** [comment]
I'm using mac, but It's probably be very similar.
If you are using nest.js cli with nodemon-debug.json
`  "exec": "node --inspect-brk -r ts-node/register -r tsconfig-paths/register src/main.ts" `
you only need to specify the port, witch by default is 9229

plus run npm/yarn script `start:debug` before debugger launch
<img width="609" alt="screen shot 2019-02-06 at 10 09 42 pm" src="https://user-images.githubusercontent.com/13748896/52373806-eaba9e00-2a5b-11e9-9309-6115e0b9fbc8.png">

**Comment by jrejaud** [comment]
You might need different syntax if you are using version 5.0.0 or beyond: 

`node --inspect=5858 -r ts-node/register path/to/ts`

See: https://github.com/TypeStrong/ts-node/issues/537

**Comment by coverboy** [comment]
![Selection_036](https://user-images.githubusercontent.com/443284/71303149-ea1ec200-23f7-11ea-9916-7c678df15c64.png)

**Comment by Evilart86** [comment]
This helps me
node version: 12.3.1
ts-node version: 8.5.4

![image](https://user-images.githubusercontent.com/20624473/71786513-d89f0200-3014-11ea-8486-627ea4364bdc.png)

**Comment by Alex-2kZharkov** [comment]
@Evilart86 Thank you very much. You saved a lot of work and time

**Comment by ayushya-work** [comment]
Facing issues in debugging NodeJS + NestJS + TypeScript application, I tried all of the above (Except Nodemon.json) 
Below is the screenshot attached. 

I am new to nodejs + nest, I am trying to fire the request from Postman and expecting to debug. 

Also do I need to do anything else before I start my "NodeJS_RUN_DEBUG" - configuration in IntelliJ Idea?

![image](https://user-images.githubusercontent.com/9247243/150634269-5673e9cf-d55d-4c57-92de-044d404e89e6.png)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
