### ISSUE TITLE
I get nom audit error for legacy version eslint 

### ISSUE THREAD

**Issue by ikaasraa** [nestjs/typescript-starter#309]
hi I get this error when I run rpm audit
└─ eslint
   ├─ ID: eslint (deprecation)
   ├─ Issue: This version is no longer supported. Please see https://eslint.org/version-support for other options.
   ├─ Severity: moderate
   ├─ Vulnerable Versions: 8.57.1
   │ 
   ├─ Tree Versions
   │  └─ 8.57.1
   │ 
   └─ Dependents
      └─ common@workspace:packages/common

please update eslint to version 9 :)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/typescript-starter/pull/310
