### ISSUE TITLE
Enforce indent consistency

### ISSUE THREAD

**Issue by elboletaire** [nestjs/typescript-starter#31]
I've started playing with nestjs, and specially, with this starter kit, and I've been a bit surprised seeing how you combine both tabs and spaces in the typescript files.

Also, the indent tslint option is disabled, and I think it shoulld be enabled to, at least, define the usage of spaces (not to say there are also files with 4 spaces instead of 2..).

As said, am a newbie, but I don't think this is correct. Is there any specific reason why you made it this way?

**Comment by kamilmysliwiec** [comment]
Hi @elboletaire,
That's true. I'm gonna spend a little bit more time on it now since v5 development part is almost entirely done.
