### ISSUE TITLE
Bump ts-node since it doesn't kill server properly on terminal close

### ISSUE THREAD

**Issue by CanKattwinkel** [nestjs/typescript-starter#36]
`ts-node 4.x` has issues when the terminal ts-node is running on gets exited **not** using `CTRL`+`C` (e.g. close the terminal). This means that the server continues to run in the background, the developer must identify the process id on the port and only then can completely terminate the process. Otherwise he receives an 'EADDRINUSE, Address already in use' error when the application is started again.

Bumping the ts-node version to 6 will fix this issue.

**Comment by kamilmysliwiec** [comment]
Upgraded in this pull request: #33

**Comment by kamilmysliwiec** [comment]
I'll merge it very soon 🙂
