### ISSUE TITLE
Commit 0adab43bf24a35067ab7dcfb2bdbb0aea8efcfa7 causing issues

### ISSUE THREAD

**Issue by kegbuna** [nestjs/typescript-starter#40]
Just getting "ENOENT: no such file or directory, open 'protorepo/UserService/UserService.proto'" when trying to `npm run start:dev`. I think the commit may have been meant for a different branch.

There's a bunch of stuff that got added to main.ts using protos and what not, so I reverted that file locally and things are working again.

I should add https://github.com/1140lex/protorepo.git is 404 for me and a submodule is pointing to it

**Comment by darrenmothersele** [comment]
Looks like something got committed accidentally?

**Comment by kamilmysliwiec** [comment]
Such a dumb mistake 🙁 Sorry, fixed already. Thanks for reporting!

**Comment by kamilmysliwiec** [comment]
You can clone repo now
