### ISSUE TITLE
hmr doesnt work

### ISSUE THREAD

**Issue by yaroslavya** [nestjs/typescript-starter#44]
I've made a clone of the master branch. Then followed the instructions from readme:
`npm run webpack`
`npm run start:hmr`
When I change the "Hello world" in the App.Service the app opened in chrome is not reloading automatically. Also theres no network activity that would show it even tried to reload. Am I missing some kind of step or its not supposed to autoreload when I change anything and save the file?
Im on Windows 10, npm 5.8.0, node v8.11.1

**Comment by kamilmysliwiec** [comment]
```
the app opened in chrome is not reloading automatically
```
You probably misunderstood hmr feature. See console output here: https://medium.com/@kammysliwiec/nest-5-the-official-release-node-js-in-2018-1b6d3a47b104

**Comment by yaroslavya** [comment]
Thanks for the explanation, Kamil, now its clear. 
To anyone who stumble upon this issue: the build rebuild is very fast and takes less than a second for me.
The website started with `webpack` and `start:hmr ` is not going to be reloaded automatically.

**Comment by xgenvn** [comment]
Hi, so do you have clue how to make it reload automatically? Should I decrease the webpack watcher timeout, or make the app more complicated to test hot reload?

**Comment by yaroslavya** [comment]
@xgenvn the point is that app is not reloaded by the browser automatically. Heres an abstract of the article that Kamil have referenced: "Thanks to the webpack hot reload feature, your application will apply changes even within 1–2 seconds, reducing amount of time spent on the compilation to an absolute minimum."
So the point of the feature is to improve the build and decrease the build time. You can see a gif in Kamils post that shows exactly that. Let me know if its not clear yet.

**Comment by xgenvn** [comment]
@yaroslavya ah, got it. Thank you ;).
