### ISSUE TITLE
.nestcli.json file missing

### ISSUE THREAD

**Issue by guyulmaz** [nestjs/typescript-starter#50]
at code
there is no .nestcli.json file existing, so for example 
nest g co about
command returning error.

>nest g co about
(node:16896) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'c:\ozel\nestjs\apps\nestjs-ts-starter-orig\.nestcli.json'
(node:16896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kamilmysliwiec** [comment]
This PR: https://github.com/nestjs/nest-cli/pull/176 will fix this issue
