### ISSUE TITLE
update package.json

### ISSUE THREAD

**Issue by guyulmaz** [nestjs/typescript-starter#51]
can we update packages to latest versions, if this dont causes any problems?

{
  "name": "nest-typescript-starter",
  "version": "1.0.0",
  "description": "Nest TypeScript starter repository",
  "license": "MIT",
  "scripts": {
    "format": "prettier --write \"src/**/*.ts\"",
    "start": "ts-node -r tsconfig-paths/register src/main.ts",
    "start:dev": "nodemon",
    "start:debug": "nodemon --config nodemon-debug.json",
    "prestart:prod": "rimraf dist && tsc",
    "start:prod": "node dist/main.js",
    "start:hmr": "node dist/server",
    "lint": "tslint -p tsconfig.json -c tslint.json",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:e2e": "jest --config ./test/jest-e2e.json",
    "webpack": "webpack --config webpack.config.js"
  },
  "dependencies": {
    "@nestjs/common": "^5.1.0",
    "@nestjs/core": "^5.1.0",
    "@nestjs/microservices": "^5.1.0",
    "@nestjs/testing": "^5.1.0",
    "@nestjs/websockets": "^5.1.0",
    "reflect-metadata": "^0.1.12",
    "rxjs": "^6.2.2",
    "typescript": "^2.8.0"
  },
  "devDependencies": {
    "@types/express": "^4.16.0",
    "@types/jest": "^23.3.1",
    "@types/node": "^10.5.5",
    "@types/supertest": "^2.0.5",
    "jest": "^23.4.2",
    "nodemon": "^1.18.3",
    "prettier": "^1.14.0",
    "rimraf": "^2.6.2",
    "supertest": "^3.1.0",
    "ts-jest": "^23.0.1",
    "ts-loader": "^4.4.2",
    "ts-node": "^7.0.0",
    "tsconfig-paths": "^3.5.0",
    "tslint": "^5.11.0",
    "webpack": "^4.16.3",
    "webpack-cli": "^3.1.0",
    "webpack-node-externals": "^1.7.2",
    "ajv": "^6.5.2"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage"
  }
}

**Comment by kamilmysliwiec** [comment]
Fixed

**Comment by mchelen** [comment]
Same issue with yarn.lock

**Comment by kamilmysliwiec** [comment]
Fixed @mchelen. Thanks for reporting!
