### ISSUE TITLE
Debugging in Docker

### ISSUE THREAD

**Issue by TristanMarion** [nestjs/typescript-starter#56]
Hello,

I would like to explain how I achieved to use VSCode debug tools while running my app in a Docker container because it took me some tricks to succeed, where could I explain the procedure and can I create a PR to push the modifications ?
Here are the changes that I would like to add :
- A new nodemon config file executing the following npm script
- A new npm script, maybe `start:debug-docker`, using `tsc` and then launching the app with `node` in inspect mode because `ts-node` in inspect mode has strange behaviours (the breakpoints in VSCode are detected but not triggered) even with a good files mapping in the `launch.json` file
- A `launch.json` configuration using `attach` to attach the container's Node inspect websocket

Thanks for the awesome tools that you create, hoping that I can help someone trying to achieve the same thing than me 😄

**Comment by kamilmysliwiec** [comment]
I would suggest creating a PR to the documentation https://github.com/nestjs/docs.nestjs.com/pulls in Recipes section (or simply create a component, I could take care of the rest [routing etc])
