### ISSUE TITLE
Why does the prestart:prod script remove the dist folder?

### ISSUE THREAD

**Issue by fvilers** [nestjs/typescript-starter#65]
Hi! I'm trying to deploy my first NestJS application and I may be doing something wrong. I can't find the documentation about building for production on the NestJS website.

From the available npm scripts, I've built the application using the `build` script and I'm trying to run it using the `start:prod` script. What bugs me is why do we have a `prestart:prod` script that removes the whole dist folder? The `start:prod` script can't start anything without it.

I suppose this is a bug and that the `prestart:prod` script is indeed a `prebuild` script. I'll gladly submit a PR if someone from the team confirms that bug.

**Comment by kamilmysliwiec** [comment]
> "prestart:prod": "rimraf dist && npm run build"

`prestart:prod` removes `dist` and afterward, builds the entire project.

**Comment by fvilers** [comment]
OK, thanks for the precision. It looks awkward to build the application on each startup, especially in a container environment. I usually build my application only once (on delivery) then start it from the `dist` folder.

**Comment by theill** [comment]
I agree with @fvilers - this should be a `prebuild` script instead as I see it.

**Comment by justinwilson-apollidon** [comment]
+1 I agree. The start of your application should assume it has already been built via your build system. For containerized environments, this is especially something that should be `prebuild`.

**Comment by kamilmysliwiec** [comment]
We actually changed that already.
