### ISSUE TITLE
rimraf should be moved from dependencies to devDependencies

### ISSUE THREAD

**Issue by ivanvs** [nestjs/typescript-starter#66]
As title is suggesting I don't see any reason why `rimraf` library should be part of `dependencies`. It is dependency of `prestart:prod` script, but I don't see that we are using it anywhere else in project. So I would like to move it to `devDependencies`.

**Comment by kamilmysliwiec** [comment]
Feel free to move it to the `devDependencies` if it's what you actually need. In the starter, it's located in `dependencies` because it's one of the steps required to build a production-ready app (removing previously compiled code).
