### ISSUE TITLE
Use typescript-tslint-plugin?

### ISSUE THREAD

**Issue by jajaperson** [nestjs/typescript-starter#71]
Many older TSLint editor plugins are deprecated in favour of the [`typescript-tslint-plugin`](https://github.com/Microsoft/typescript-tslint-plugin). This requires a tiny bit of configuration in `tsconfig.json`, which should probably be implemented in the starter.

**Comment by kamilmysliwiec** [comment]
We will probably switch at some point, but there is no plan for it yet.
